# Fan configuration
time: 60
alerts:
- message: Error rate
  text: ERROR 
  thrshold: 20
  playbook: error
- message: Machine rebooted
  text: reboots
  thrshold: 2
  playbook: reboot
- message: Critial errors rate
  text: CRITICAL
  thrshold: 1
  playbook: critical
